config/routes.rb
Rails.application.routes.draw do
    resources :posts, except: :new
  get 'searchcheck/search'
  
  get 'posts/new/:lat/:lng' => 'posts#new', as: 'new_post'

  get 'home/csvsave'
  
  get 'posts_ajax/:post_id' => 'posts#ajaxIndex'

  root 'posts#index'
  
  resources :posts do
    collection do
      get:search
    end
  end

end

app/models/beerdb.rb
class Beerdb < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates_presence_of :title, :content
    
    searchable do
        text :title, :content, :hashtag
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  require 'csv'
  
  def csvsave
    csv_text = File.read('public/beerdb_please.csv', :encoding =>'EUC-KR', :headers => true)
    keys = ['num', 'name', 'brewery', 'style', 'alcohol', 'fruit', 'ibu', 'text']
    @save = CSV.parse(csv_text).map {|a| Hash[keys.zip(a)]}
    i=1
    while i < @save.length-1
    @class = Beerdb.new
    @class.num = @save[i].to_a[0][1]
    @class.name = @save[i].to_a[1][1]
    @class.brewery = @save[i].to_a[2][1]
    @class.style = @save[i].to_a[3][1]
    @class.alcohol = @save[i].to_a[4][1]
    @class.fruit = @save[i].to_a[5][1]
    @class.ibu = @save[i].to_a[6][1]
    @class.text = @save[i].to_a[7][1]
    @class.save
    i = i+1
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def search
    @posts = Post.search do
      keywords params[:query]
    end.results
    
    respond_to do |format|
      format.html { render :action => "index" }
      format.xml { render :xml => @posts }
    end
  end
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    
    @lat = params[:lat].sub("a",".")
    @lng = params[:lng].sub("a",".")
    
    @post = Post.new(:x => @lat, :y => @lng)
    
    @post.x = params[:lat]
    @post.y = params[:lng]
    @post.save
    
    #query = "INSERT INTO post (x, y) VALUES ('#{@post.x}', '#{@post.y}')  "
    #query = "INSERT INTO bookmark (title , url, tags) VALUES (#{@user_new.title}, #{@user_new.url}, #{tags[0]})  "

    #Post.connection.execute(query);
  end
  
  def ajaxIndex
    if params[:post_id]
      @post = Post.find(params[:post_id])
    end
    respond_to do |format|
      format.js { render 'index.js.erb' }
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post =Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :hashtag, :x, :y)
    end
end

app/controllers/searchcheck_controller.rb
class SearchcheckController < ApplicationController
  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchcheck_helper.rb
module SearchcheckHelper
end

app/views/home/csvsave.html.erb
<h1>Home#csvsave</h1>
<p>Find me in app/views/home/csvsave.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :hashtag %><br>
    <%= f.text_field :hashtag %>
  </div>
  <div class="field">
    <%= f.hidden_field :x, id: :post_x , step: :any, value: @lat%>
  </div>

  <div class="field">
    <%= f.hidden_field :y, id: :post_y , step: :any, value: @lng%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  console.log(<%=@post.y%>);
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<head>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArXEvyWLOJs-JGPMjqpTSRMYgVyol8dX8"></script>
            <style>
        #map {
            height: 600px;
            width: 100%;
        }

    </style>

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>
</head>
<body>

<h2>Hashtags Search</h2>

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">

<table id="myTable">
  <tr class="header">
    <th style="width:60%;">Hashtags</th>
  </tr>
  <tr>
    <td>a</td>
  </tr>
  <tr>
    <td>b</td>
  </tr>
  <tr>
    <td>c</td>
  </tr>

</table>

<script>
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>



<h2> Search </h2>
<br>
<%= form_tag search_posts_path, :onkeyup => 'myFunc()', :id => "searchspot", :method => :get do %>
<%= text_field_tag :query, params[:query] %> <%= submit_tag "Search!" %>
<% end %>

<script>
function myFunc() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("searchspot");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>


<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Hashtag</th>
      <th>X</th>
      <th>Y</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.hashtag %></td>
        <td><%= post.x %></td>
        <td><%= post.y %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Post', new_post_path %>

<br><br>
<div class="map-posts" style="display: float;">
  
</div>


<br><br>


<div>
<tbody>
    <%# @post.each do |p| %>
      <tr>
        <td><%#= p.title %></td>
        <td><%#= p.content %></td>
    <%# end %>
  </tbody>
</table>
</div>


<div class="bodywrapper">
<div class="container">
<div id="map"></div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArXEvyWLOJs-JGPMjqpTSRMYgVyol8dX8"></script>
<script>
        var seoul = {lat: 37.557216,lng: 126.987319};
        var smap = new google.maps.Map(document.getElementById('map'), {
            zoom: 12,
            center: seoul
            
        });
        
        
        var first =  {lat: 37.4987493,lng: 126.9954321};
        //var second = {lat: 37.5567904,lng: 126.973718};
        var second = new google.maps.LatLng(37.5567904,126.973718);
        var marker1 = new google.maps.Marker({position: first,title: "크래프트 브로스", label: "크래프트 브로스", map: smap, icon:'beer2.png'});
        var marker2 = new google.maps.Marker({position: second, label: "아트 몬스터", map: smap, icon:'beer2.png'});

        var infowindow = new google.maps.InfoWindow({
            content: "Brewery"
        });
        
        marker1.addListener('click', function() {
          infowindow.open(smap,marker1);
        });
        
        marker2.addListener('click', function() {
          infowindow.open(smap,marker2);
        });
        
 /*       google.maps.event.addListener(smap, 'click', function(event) {
            //placeMarker(smap, event.LatLng);
        //});
        
        //function placeMarker(map, location) {
            //console.log("");
            var marker = new google.maps.Marker({
                position: event.LatLng,
                map: smap
            });
            var infowindow = new google.maps.InfoWindow({
                content: 'Latitude: ' + event.lat() + 
                '<br>Longtitude: ' + event.lng()
                
            });
             console.log("zzz");
            infowindow.open(smap,marker);
        });
        */
        
        
  var markers = [];      
  <% @posts .each do |post| %>
  var marker = new google.maps.Marker({
    position: {lat: <%= post.x %>, lng: <%= post.y %>},
    map: smap,
    title: "<%= post.title %>",
    icon: "<%= asset_path 'foodTruck2.png' %>"
  });
  marker.addListener('click', function(){
    console.log("hello");
    $.ajax({
      url: "/posts_ajax/"+<%= post.id %>
    });
  })
  console.log(<%=post.x%>);
  marker.setMap(smap);


  var beforMarker;
  google.maps.event.addListener(smap, 'click', function(event) {
    console.log("hi");
    var contentString = "<div><a href='/posts/new/"+event.latLng.lat().toString().replace(".","a")+"/"+event.latLng.lng().toString().replace(".","a")+"'>브루어리 추가!</a></div>";
/*      var marker = new google.maps.InfoWindow({
    position: {lat: 37.55628, lng: 126.93694};
  }); */
  //  <%#= @lat %> = event.latLng.lat();
    console.log(event.latLng.lat());
    
      
    var marker = new google.maps.Marker({
      position: event.latLng,
      map: smap
    });
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    console.log("zzz");

    infowindow.open(smap,marker);

  });
  <%end%>      
$()


</script>
</div>
</div>
<!--<div class="footer">ⓒ 2018  Beer SNS</div>-->
</body>

app/views/posts/index.js.erb
$(".map-posts").html("<div><%= @post.title%></div><div><%= @post.content%></div><div><!--img src='<%= @post.hashtag %>'--></div>").hide().fadeIn(500);

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Hashtag:</strong>
  <%= @post.hashtag %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', index %>

app/views/searchcheck/search.html.erb
<h1>Searchcheck#search</h1>
<p>Find me in app/views/searchcheck/search.html.erb</p>

<form name="Survey" method="get" action="">
  <div class= "survey">  
    <p>
    <label for="Alcohol">도수</label>
    <input type="checkbox" name="Alcohol" value=1> 4도 이하
    <input type="checkbox" name="Alcohol" value=2> 6도 이하
    <input type="checkbox" name="Alcohol" value=3> 8도 이하
    <input type="checkbox" name="Alcohol" value=4> 10도 이하
    <input type="checkbox" name="Alcohol" value=5> 10도 이상
    </p>

    <p>
    <label for="Fruit">과일향</label>
    <input type="checkbox" name="Fruit" value=1> 유
    <input type="checkbox" name="Fruit" value=2> 무
    </p>

    <p>
    <label for="IBU">쓴 맛(IBU기준)</label>
    <input type="checkbox" name="IBU" value=1> 0-20
    <input type="checkbox" name="IBU" value=2> 21-40
    <input type="checkbox" name="IBU" value=3> 41-60
    <input type="checkbox" name="IBU" value=4> 61-80
    <input type="checkbox" name="IBU" value=5> 81-100
    </p>
    </div>
    
    <input type="submit" value="SUBMIT" style="float: right;">

  </form>